# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [12]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())
# A config is a set of settings and environment information that affects how software runs

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10) # null means "nothing is here"

#### 4. How to find the memory size of any array (★☆☆)

In [15]:
print(null_vector.size) # number of elements
print(null_vector.itemsize) # bytes per element
print(null_vector.nbytes) # total bytes 

10
8
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
nv = np.zeros(10)
nv[4] = 1
print(nv)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
print(np.arrange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
nv1 = np.arange(10)
print(nv1[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [27]:
A = np.array([1,2,0,0,4,0])
print(np.where(A != 0))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
hint: np.eye


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
print(np.random.random((3,3,3)))

[[[0.71686829 0.54599359 0.74439316]
  [0.27891421 0.88749504 0.5408113 ]
  [0.40659402 0.96345303 0.76844151]]

 [[0.70897533 0.61947855 0.00769119]
  [0.48164167 0.26605595 0.66843744]
  [0.27089911 0.30523949 0.4899017 ]]

 [[0.61759179 0.86231162 0.23989581]
  [0.3325725  0.27438709 0.96282877]
  [0.80666815 0.52380696 0.43305782]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
M = np.random.random((10,10))
print(np.min(M))
print(np.max(M))

0.015358593975735024
0.9990557612690238


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
V = np.random.random(30)
print(np.mean(V))

0.44015638595363155


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
B1I0 = np.ones((3,3))
B1I0[1,1] = 0
print(B1I0)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [8]:
A = np.ones((3,3))
A = np.pad(A, pad_width = 1, mode = 'constant', constant_values = 0)
print(A)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [9]:
hint(17)

hint: NaN = not a number, inf = infinity


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
print(np.diag([1,2,3,4], k = 0))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [14]:
Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [6]:
print(tuple(map(int, np.unravel_index(99, (6,7,8)))))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [7]:
print(np.tile([[0,1],
               [1,0]], (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 

In [8]:
Z = np.random.random((5,5))
Z_normalized = (Z - Z.min())/(Z.max() - Z.min())
print(Z_normalized)

[[0.79973484 0.44340084 0.71503058 0.45897124 0.60854096]
 [0.48536818 0.048354   0.93302431 0.3801461  0.1942407 ]
 [0.88652801 0.75083718 0.92684    0.68121204 0.80146758]
 [0.57307246 0.         0.11228758 0.45031961 1.        ]
 [0.44993438 0.31421481 0.09310724 0.77095793 0.62786613]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [10]:
color = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
rng = np.random.default_rng()
A = rng.integers(0,10, size = (5,3))
B = rng.integers(0,10, size = (3,2))
print(np.matmul(A,B))

[[54 24]
 [97 64]
 [78 85]
 [77 56]
 [87 51]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [5]:
Z  = np.arange(11)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [7]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)
print(Z**Z) # element-wise exponentiation
print(2 << Z >> 2) # element-wise bitwise shift
print(Z < -Z) # element-wise comparison(check is each element of Z is less than its negation)
print(1j * Z) # element-wise multiplication with imaginary unit
print(Z / 1 / 1) # element-wise division, the result is a float array, not an integer array
print(Z < Z > Z) # element-wise comparison (illegal)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0)) # division by zero(undefined)
print(np.array(0) // np.array(0)) # floor division by zero(undefined)
print(np.array([np.nan]).astype(int)) # nan to int (undefined)

#### 29. How to round away from zero a float array ? (★☆☆)

In [12]:
Z = np.array([-1.7, -1.5, -0.2, 0.1, 0.6, 1.9, 2.5, 3.3])
# to round away from zero, ignore the sign first, round up, then put the sign back
result = np.copysign(np.ceil(np.abs(Z)), Z)
print(result)

[-2. -2. -1.  1.  1.  2.  3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
A = np.array([0,9,0,2,9,6])
B = np.array([0,6,1,3,9,8])
common = np.intersect1d(A,B) # returns sorted unique values
print(common)

[0 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [14]:
np.seterr(all = "ignore")
print(np.array(0) / np.array(0))

nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [15]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64("today") - np.timedelta64(1, "D")
today = np.datetime64("today")
tomorrow = np.datetime64("today") + np.timedelta64(1, "D")

print("yesterday: ", yesterday)
print("today: ", today)
print("tomorrow: ", tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [2]:
dates = np.arange('2026-07', '2026-08', dtype = 'datetime64[D]')
print(dates)

['2026-07-01' '2026-07-02' '2026-07-03' '2026-07-04' '2026-07-05'
 '2026-07-06' '2026-07-07' '2026-07-08' '2026-07-09' '2026-07-10'
 '2026-07-11' '2026-07-12' '2026-07-13' '2026-07-14' '2026-07-15'
 '2026-07-16' '2026-07-17' '2026-07-18' '2026-07-19' '2026-07-20'
 '2026-07-21' '2026-07-22' '2026-07-23' '2026-07-24' '2026-07-25'
 '2026-07-26' '2026-07-27' '2026-07-28' '2026-07-29' '2026-07-30'
 '2026-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [4]:
A = np.array([1., 2., 3.])
B = np.array([4., 5., 6.])

np.add(A,B,out = B)
np.divide(A,2, out = A)
np.negative(A, out = A)
np.multiply(A,B, out = A)

print(A)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [5]:
Z = np.random.uniform(0, 10, 5)
print(Z)

print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))
print(Z // 1)

[5.3295195  2.52931989 5.82690156 7.07343845 3.3479457 ]
[5. 2. 5. 7. 3.]
[5 2 5 7 3]
[5. 2. 5. 7. 3.]
[5. 2. 5. 7. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [10]:
Z = np.zeros((5,5))
Z += np.arange(5)

print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
    for x in range(10):
        yield x

Z = np.fromiter(generator(), dtype = int, count = -1)
print(Z)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)